namespace IbsRestApi.Entities.iMoneytor;

public partial class LnTerminate
{
    public int IdLnTerminate { get; set; }
    public int? LoanId { get; set; }
    public string? TerminationReason { get; set; }
    public DateTime? TerminationDate { get; set; }
    public string? TerminationType { get; set; }
    public string? IssueType { get; set; }
    public decimal? IssueRate { get; set; }
    public decimal? QtySold { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal? CostPrice { get; set; }
    public decimal? MartketValue { get; set; }
    public DateTime? NewEffectiveDate { get; set; }
    public DateTime? NewMaturityDate { get; set; }
    public string? TransferNo { get; set; }
    public string? ContractNoteNo { get; set; }
    public decimal? StampDuty { get; set; }
    public decimal? Commission { get; set; }
    public decimal? Vat { get; set; }
    public decimal? SecFees { get; set; }
    public decimal? NseCscsfees { get; set; }
    public decimal? OtherFees { get; set; }
    public decimal? Premuim { get; set; }
    public decimal? Discount { get; set; }
    public decimal? TransactionCost { get; set; }
    public decimal? SalesProceed { get; set; }
    public decimal? CumInterest { get; set; }
    public string? Status { get; set; }
    public string? Comments { get; set; }
    public string? VoucherNo { get; set; }
    public decimal? Taxes { get; set; }
    public bool? IgnoreOsInterest { get; set; }
    public decimal? NewNorminalCost { get; set; }
    public decimal? ProfLoss { get; set; }
    public string? ContractNoteId { get; set; }
    public DateTime? SettlementDate { get; set; }
    public bool? ChangePaymentTerms { get; set; }
    public decimal? UnEarnedInterest { get; set; }
    public DateTime? GlpostDate { get; set; }
    public string? GlPostPeriod { get; set; }
    public int? DaysElapse { get; set; }
    public bool? OverrideCoupon { get; set; }
    public int? CouponDays { get; set; }
    public int? IdLoanMandateDetails { get; set; }
    public decimal? PremDisc2Post { get; set; }
    public DateTime? LastPostDate { get; set; }
    public decimal? BalanceWriteOff { get; set; }
    public decimal? ManualSalesCoupon { get; set; }
    public string? BrokerId { get; set; }
    public decimal? PremDisc4Period { get; set; }
    public DateTime? TransactionDate { get; set; }
    public decimal? PremDiscSold { get; set; }
    public decimal? PremDiscBf { get; set; }
    public decimal? PremDisc2date { get; set; }
    public decimal? PremDiscBal { get; set; }
    public decimal? PremDiscCf { get; set; }
    public decimal? PremDiscUnSold { get; set; }
    public decimal? PremDiscSold2 { get; set; }
    public decimal? NewYieldRate { get; set; }
    public decimal? QtyUnitBf { get; set; }
    public decimal? PremDiscIncep2Date { get; set; }
    public DateTime? LastWriteOffDate { get; set; }
    public decimal? NorminalValueBf { get; set; }
    public decimal? PrnCostBf { get; set; }
    public decimal? PrnCostSold { get; set; }
    public decimal? PrnCostCf { get; set; }
    public decimal? TotalCost { get; set; }
    
    public decimal? PremDisc2Reverse { get; set; }
    public decimal? Interest2Reverse { get; set; }
    public decimal? UnRealiseGainLoss { get; set; }
    public decimal? CostOfBond { get; set; }
    public string? CapturedBy { get; set; }
    public string? IdBankaccount { get; set; }
}
