namespace IbsRestApi.Entities.iMoneytor;

public partial class PortfolioGroup
{
    public int IdPortfolioGroup { get; set; }
    public string? PortfolioGroup1 { get; set; }
    public bool? Segregated { get; set; }
    public bool? EthicalGroup { get; set; }
    public decimal? MinAmount { get; set; }
    public decimal? MaxAmount { get; set; }
    public int? MinAge { get; set; }
    public int? MaxAge { get; set; }
    public decimal? MinRiskAppetite { get; set; }
    public decimal? MaxRiskAppetite { get; set; }
    public string? IdRelationshipManager { get; set; }
    public string? MainAccount { get; set; }
    public string? FeesIncomeReserve { get; set; }
    public string? ManagementFeesIncomeAccount { get; set; }
    public string? IncomeFeesAccountNo { get; set; }
    public string? IncentiveIncomeActNo { get; set; }
    public string? InterestExpenseActNo { get; set; }
    public string? InterestIncomeActNo { get; set; }
    public decimal? MinTimeFactor { get; set; }
    public decimal? MaxTimeFactor { get; set; }
    public int? WithdrawalFrequency { get; set; }
    public string? FundCode { get; set; }
    public string? Cscsid { get; set; }
    public string? InvestorAccountNo { get; set; }
    public string? VataccountNo { get; set; }
    public string? IdBizUnit { get; set; }
    public string? BankGlActNo { get; set; }
    public int? IdPortfolioGroupClassification { get; set; }
    public string? SalesGainLossGlActNo { get; set; }
    public string? IdBankAccount01 { get; set; }
    public string? IdBankAccount02 { get; set; }
    public string? ForexGainGlActNo { get; set; }
    public string? ForexLossGlActNo { get; set; }
    public string? MainAccountWithdraw { get; set; }
    public string? CustodianFeesPayable { get; set; }
    public string? RequlatoryFeesPayable { get; set; }
    public string? ManagementFeesIncomeAccountPfc { get; set; }
    public string? ManagementFeesIncomeAccountRegulator { get; set; }
    public string? VatAccountNoPfc { get; set; }
    public string? VatAccountNoRequlator { get; set; }
    public string? VatExpActNoAssetMgr { get; set; }
    public string? VatExpActNoCustodian { get; set; }
    public string? VatExpActNoRegulator { get; set; }
    public string? ContributionActNo { get; set; }
    public string? AllocationActNo { get; set; }
    
    public string? WithdrawalPayableActNo { get; set; }
    public string? MainAccountCcenter { get; set; }
    public string? FeesIncomeReserveCcenter { get; set; }
    public string? ManagementFeesIncomeAccountCcenter { get; set; }
    public string? IncomeFeesAccountNoCcenter { get; set; }
    public string? IncentiveIncomeActNoCcenter { get; set; }
    public string? InterestExpenseActNoCcenter { get; set; }
    public string? InterestIncomeActNoCcenter { get; set; }
    public string? VataccountNoCcenter { get; set; }
    public string? BankGlActNoCcenter { get; set; }
    public string? SalesGainLossGlActNoCcenter { get; set; }
    public string? ForexGainGlActNoCcenter { get; set; }
    public string? ForexLossGlActNoCcenter { get; set; }
    public string? MainAccountWithdrawCcenter { get; set; }
    public string? CustodianFeesPayableCcenter { get; set; }
    public string? RequlatoryFeesPayableCcenter { get; set; }
    public string? ManagementFeesIncomeAccountPfcCcenter { get; set; }
    public string? ManagementFeesIncomeAccountRegulatorCcenter { get; set; }
    public string? VatAccountNoPfcCcenter { get; set; }
    public string? VatAccountNoRequlatorCcenter { get; set; }
    public string? VatExpActNoAssetMgrCcenter { get; set; }
    public string? VatExpActNoCustodianCcenter { get; set; }
    public string? VatExpActNoRegulatorCcenter { get; set; }
    public string? ContributionActNoCcenter { get; set; }
    public string? AllocationActNoCcenter { get; set; }
    public string? WithdrawalPayableActNoCcenter { get; set; }
    public string? Cash1AccountNo { get; set; }
    public string? Cash1AccountNoCcenter { get; set; }
    public string? Cash2AccountNo { get; set; }
    public string? Cash2AccountNoCcenter { get; set; }
    public bool? PostWithdrawalToPayable { get; set; }
}
