namespace IbsRestApi.Entities.iMoneytor;

public partial class Preference
{
    public int IdPreferences { get; set; }
    public string? CompanyName { get; set; }
    public string? Address01 { get; set; }
    public string? Address02 { get; set; }
    public string? IdState { get; set; }
    public string? IdHomeBranch { get; set; }
    public string? FinYearBegin { get; set; }
    public string? MailType { get; set; }
    public string? Smtphost { get; set; }
    public string? Smtpport { get; set; }
    public string? SenderAddress { get; set; }
    public string? SenderName { get; set; }
    public string? ReplyToAddress { get; set; }
    public bool? Post2Gl { get; set; }
    public decimal? ReturnChqCharge { get; set; }
    public bool? Link2MoneyBook { get; set; }
    public short? ReceiptNoLenght { get; set; }
    public string? IdApplication { get; set; }
    public string? IdProductLine { get; set; }
    public string? IdLocation { get; set; }
    public decimal? CotRate { get; set; }
    public bool? ActivateWorkFlow { get; set; }
    public string? MoneyBookDatabaseName { get; set; }
    public bool? RequireGsmNumber { get; set; }
    public byte? GsmnumberLenght { get; set; }
    public string? Gsm1stThreeDigit { get; set; }
    public string? Money4LodgementActNo { get; set; }
    public string? Money4PaymentActNo { get; set; }
    public string? FeesIncomeActNo { get; set; }
    public string? IdLocalCurrency { get; set; }
    public bool? TrackPortfolio { get; set; }
    public decimal? VatRate { get; set; }
    public decimal? WithTaxRate { get; set; }
    public string? GlexportFile { get; set; }
    public bool? MaketValueValuationBasis { get; set; }
    public string? UnitValueFolder { get; set; }
    public string? Gl2moneytorFolder { get; set; }
    public int? AutorunTimer { get; set; }
    public bool? Link2Pfc { get; set; }
    public string? Glsoftware { get; set; }
    public bool? CalculateBrokerCommision { get; set; }
    public bool? ForceApprovalLimit { get; set; }
    public bool? BreakCompliance { get; set; }
    public string? Deposit2BrokerActNo { get; set; }
    public string? ConfigSystemFor { get; set; }
    public DateTime? NextFeesDeductionDate { get; set; }
    public int? DeductFeesEvery { get; set; }
    public int? DaysOfGrace { get; set; }
    public int? MinimumDaysInPeriodB4fees { get; set; }
    public decimal? Provision4LiquidationRate { get; set; }
    public bool? SummarizePortfolioStatement { get; set; }
    public bool? UseNetDividend4Valuation { get; set; }
    public string? ShortCompanyName { get; set; }
    public string? WitholdTaxGlActNo { get; set; }
    public bool? ValuateDeposit4SharesAtMarketPrice { get; set; }
    public bool? AutoPortfolioCode { get; set; }
    public string? BrokerPayableActNo { get; set; }
    public string? BrokerReceivableActNo { get; set; }
    public string? BrokerPayable2ActNo { get; set; }
    public string? BrokerReceivable2ActNo { get; set; }
    public string? IntRecableActNo { get; set; }
    public string? XmlexportPath { get; set; }
    public bool? ReportPayRecAbleInValutaion { get; set; }
    public bool? ClosedPfa { get; set; }
    public string? XmlAuthorisedSignatory { get; set; }
    public int? PostChangeInShareValue { get; set; }
    public byte[]? Logo { get; set; }
    public string? StockBrokerTableName { get; set; }
    public bool? DividendReduceCost { get; set; }
    public bool? CashForecastWorkFlow { get; set; }
    public bool? AutoReceiveOnMaturity { get; set; }
    public bool? SplitEquityCost { get; set; }
    public bool? SplitEquitySalesProceed { get; set; }
    public string? OtherIncomeActNo { get; set; }
    public bool? ForexRevaluation { get; set; }
    public bool? GlobalCompliance { get; set; }
    public string? RecogniseEquityOn { get; set; }
    public bool? DoNotAutoPostPurchaseSettlement { get; set; }
    public bool? DoNotAutopostDisposalSettlement { get; set; }
    public bool? DoNotPost2GlforPortfolioMovement { get; set; }
    public bool? AutoLoadAlert { get; set; }
    public bool? SkipVerification { get; set; }
    public bool? MonthlyChangeInShareValue { get; set; }
    public bool? SumarizedChangeInShareValue { get; set; }
    public bool? Ifrsvaluation { get; set; }
    public byte? UseIrr4Yield { get; set; }
    public short? YieldDecPlaces { get; set; }
    public byte? BondAmortYieldMethod { get; set; }
    public bool? PostPortfolioMovMntByTransType { get; set; }
    public bool? UseBrokerSettlementModule { get; set; }
    public bool? PostFromContributionAccount { get; set; }
    public string? MailingList { get; set; }
    public bool? IgnoreWtaxOnDividend { get; set; }
    public DateTime? IgnoreWtaxDate { get; set; }
    public string? AuthUser { get; set; }
    public string? AuthPassWord { get; set; }
    public string? WebSite { get; set; }
    public bool? PostBondChangeInMarketValue { get; set; }
    public bool? ThreeStepWorkFlow { get; set; }
    public short? RollOverMax { get; set; }
    public string? StampDutyGlactNo { get; set; }
    public decimal? StampDutyAmount { get; set; }
    public string? PfaCode { get; set; }
    public bool? SimpleCashforecast { get; set; }
    public bool? PickGlfromExt { get; set; }
    public bool? MergedCorporateAction { get; set; }
    public bool? SimpleTransferLetterVersion { get; set; }
    public bool? AutomatedSignature { get; set; }
    public bool? ExposureBasedOnAccruedInterest { get; set; }
    public bool? PostTbillsMark2Market { get; set; }
    public decimal? MaxMmarketWam { get; set; }
    public bool? EnforceMmarketWam { get; set; }
    public bool? MultiAgents { get; set; }
    public bool? AutoReceiptNumber { get; set; }
    public bool? AutoPost2Gl { get; set; }
    public bool? SecureEmailAlways { get; set; }
    public bool? SecureEmailStartTls { get; set; }
    public bool? NetOfFeesPortfolioYield { get; set; }
    public bool? ActivateXcelerator { get; set; }
    public string? Money4LodgementActNoCcenter { get; set; }
    public string? Money4PaymentActNoCcenter { get; set; }
    public string? FeesIncomeActNoCcenter { get; set; }
    public string? IntRecableActNoCcenter { get; set; }
    public string? WitholdTaxGlActNoCcenter { get; set; }
    public string? OtherIncomeActNoCcenter { get; set; }
    public string? StampDutyGlactNoCcenter { get; set; }
    public bool? BondInterestFromInceptionToDate { get; set; }
    public bool? ApplyStampDuty { get; set; }
    public decimal? MinStampDutyAmount { get; set; }
    public short? XirrGeneratorMethod { get; set; }
    public bool? IgnoreTransactionCost { get; set; }
    public DateTime? IgnoreTransCostDate { get; set; }
    public bool? ApplyAutoRatesOnFunding { get; set; }
    public string? IdLocalCountry { get; set; }
    public bool? PayOutViaIsignProcess { get; set; }
    public string? PayableWithTaxActNo { get; set; }
    public string? Cash1AccountNo { get; set; }
    public string? Cash2AccountNo { get; set; }
    public string? PfcName { get; set; }
    public string? Pfc2PfaFolder { get; set; }
    public string? Pfa2PfcFolder { get; set; }
    public string? PfcAddress01 { get; set; }
    public string? PfcAddress02 { get; set; }
    public string? IdPfcState { get; set; }
    public string? PfcContact { get; set; }
    public string? PfcTelephones { get; set; }
    public string? PfcBankCode { get; set; }
    public string? PfcEmail { get; set; }
    public bool? GroupValuationRun { get; set; }
}
