namespace IbsRestApi.Entities.iMoneytor;

public partial class Syncobj0x4146433536424535
{
    public int IdPortfolio { get; set; }
    public int? IdPortfolioGroup { get; set; }
    public string? Portfolio { get; set; }
    public string? ContactPerson { get; set; }
    public string? Address01 { get; set; }
    public string? Address02 { get; set; }
    public string? IdState { get; set; }
    public string? Telephones { get; set; }
    public string? GsmNo { get; set; }
    public string? Email { get; set; }
    public bool? ApplyCompliance { get; set; }
    public bool? DoNotEarnComision { get; set; }
    public decimal? ManagementFees { get; set; }
    public decimal? IncomeFeesRate { get; set; }
    public string? MainAccount { get; set; }
    public string? ManagementFeesIncomeAccount { get; set; }
    public string? IncomeFeesAccountNo { get; set; }
    public string? Status { get; set; }
    public string? SfkaccountCode { get; set; }
    public bool? UnitBased { get; set; }
    public decimal? InitialUnitValue { get; set; }
    public decimal? TotalUnits { get; set; }
    public decimal? OfferPrice { get; set; }
    public decimal? BidPrice { get; set; }
    public decimal? NetAssetValue { get; set; }
    public decimal? BrokerageFee { get; set; }
    public bool? BearBrokersComision { get; set; }
    public string? FeesIncomeReserve { get; set; }
    public decimal? PfamgtFees { get; set; }
    public decimal? PfcmgtFees { get; set; }
    public decimal? PcmmgtFees { get; set; }
    public string? SurName { get; set; }
    public string? FirstName { get; set; }
    public decimal? InitialInvestmentAmount { get; set; }
    public string? IdReferedByBranch { get; set; }
    public string? ReferedByOfficer { get; set; }
    public bool? OnLineAccess { get; set; }
    public string? PinNo { get; set; }
    public string? AccountClass { get; set; }
    public bool? DocumentationWaved { get; set; }
    public bool? SearchConducted { get; set; }
    public bool? SearchOkay { get; set; }
    public string? SearchComments { get; set; }
    public DateTime? DateOfBirth { get; set; }
    public string? Sex { get; set; }
    public string? EmploymentStatus { get; set; }
    public int? IdEmployer { get; set; }
    public DateTime? AccountOpenDate { get; set; }
    public DateTime? AccountClosureDate { get; set; }
    public string? EquityValuationMedhod { get; set; }
    public string? RealEstateValuationMethod { get; set; }
    public string? FixedIncomeValuationMethod { get; set; }
    public string? ReportDeliveryMethod { get; set; }
    public bool? XMasGift { get; set; }
    public DateTime? ContractDate { get; set; }
    public int? ContractTenor { get; set; }
    public DateTime? ExpireDate { get; set; }
    public int? RenewalCount { get; set; }
    public DateTime? LastRenuwalDate { get; set; }
    public string? MgtFeesBasedOn { get; set; }
    public byte? DeductMgtFeesEvery { get; set; }
    public DateTime? NextMgtFeeDeductDate { get; set; }
    public DateTime? LastMgtFeeDeductDate { get; set; }
    public string? IncentiveBasedOn { get; set; }
    public int? IdIncentiveBenchmark { get; set; }
    public string? IncentiveCalcMethod { get; set; }
    public decimal? GuaranteeYield { get; set; }
    public byte? DeductIncentiveEvery { get; set; }
    public decimal? IncentiveRate { get; set; }
    public int? WaiverPeriod { get; set; }
    public DateTime? NextIncentiveDueDate { get; set; }
    public DateTime? LastIncentiveDueDate { get; set; }
    public decimal? CrIntRate { get; set; }
    public decimal? DrIntRate { get; set; }
    public decimal? MinCrBalance { get; set; }
    public string? EarlyTerminationPenalty { get; set; }
    public string? WaiverNotes { get; set; }
    public string? Comments { get; set; }
    public string? IncentiveIncomeActNo { get; set; }
    public int? IntFreeDaysOnDrBalance { get; set; }
    public string? InterestExpenseActNo { get; set; }
    public string? InterestIncomeActNo { get; set; }
    public decimal? RiskFactor { get; set; }
    public decimal? TimeFactor { get; set; }
    public string? MgtFeesPer { get; set; }
    public int? CompoundEvery { get; set; }
    public DateTime? LastCompoundDate { get; set; }
    public string? IdCurrency { get; set; }
    public bool? ApplyWitholdingTax { get; set; }
    public bool? ApplyVat { get; set; }
    public decimal? PenaltyMgtFeesRate { get; set; }
    public string? CapturedBy { get; set; }
    public string? ApprovedBy { get; set; }
    public string? IdRelationshipManager { get; set; }
    public string? Pword { get; set; }
    public string? Cscsid { get; set; }
    public string? InvestorActNo { get; set; }
    public DateTime? ValuationDate { get; set; }
    public bool? ChargeFeesOnGrossNav { get; set; }
    public int? IdPortfolioContributor { get; set; }
    public bool? DeliverReportByHold { get; set; }
    public bool? DeliverReportByPost { get; set; }
    public bool? DeliverReportByEMail { get; set; }
    public int? LockInDays { get; set; }
    public decimal? LockInPenaltyRate { get; set; }
    public string? ShortName { get; set; }
    public decimal? BuyComisionRate { get; set; }
    public decimal? SellComisionRate { get; set; }
    public int? RegistrarId { get; set; }
}
