namespace IbsRestApi.Entities.iMoneytor;

public partial class Syncobj0x4442393134383637
{
    public int IdPreferences { get; set; }
    public string? CompanyName { get; set; }
    public string? Address01 { get; set; }
    public string? Address02 { get; set; }
    public string? IdState { get; set; }
    public string? IdHomeBranch { get; set; }
    public string? FinYearBegin { get; set; }
    public string? MailType { get; set; }
    public string? Smtphost { get; set; }
    public string? Smtpport { get; set; }
    public string? SenderAddress { get; set; }
    public string? SenderName { get; set; }
    public string? ReplyToAddress { get; set; }
    public bool? Post2Gl { get; set; }
    public decimal? ReturnChqCharge { get; set; }
    public bool? Link2MoneyBook { get; set; }
    public short? ReceiptNoLenght { get; set; }
    public string? IdApplication { get; set; }
    public string? IdProductLine { get; set; }
    public string? IdLocation { get; set; }
    public decimal? CotRate { get; set; }
    public bool? ActivateWorkFlow { get; set; }
    public string? MoneyBookDatabaseName { get; set; }
    public bool? RequireGsmNumber { get; set; }
    public byte? GsmnumberLenght { get; set; }
    public string? Gsm1stThreeDigit { get; set; }
    public string? Money4LodgementActNo { get; set; }
    public string? Money4PaymentActNo { get; set; }
    public string? FeesIncomeActNo { get; set; }
    public string? IdLocalCurrency { get; set; }
    public bool? TrackPortfolio { get; set; }
    public decimal? VatRate { get; set; }
    public decimal? WithTaxRate { get; set; }
    public string? PfaCode { get; set; }
    public string? GlexportFile { get; set; }
    public string? PfcName { get; set; }
    public string? Pfc2PfaFolder { get; set; }
    public string? Pfa2PfcFolder { get; set; }
    public bool? MaketValueValuationBasis { get; set; }
    public string? UnitValueFolder { get; set; }
    public string? Gl2moneytorFolder { get; set; }
    public int? AutorunTimer { get; set; }
    public bool? Link2Pfc { get; set; }
    public string? PfcAddress01 { get; set; }
    public string? PfcAddress02 { get; set; }
    public string? IdPfcState { get; set; }
    public string? PfcContact { get; set; }
    public string? PfcTelephones { get; set; }
    public string? Glsoftware { get; set; }
    public bool? CalculateBrokerCommision { get; set; }
    public bool? ForceApprovalLimit { get; set; }
    public bool? BreakCompliance { get; set; }
    public string? Deposit2BrokerActNo { get; set; }
    public string? ConfigSystemFor { get; set; }
    public DateTime? NextFeesDeductionDate { get; set; }
    public int? DeductFeesEvery { get; set; }
    public int? DaysOfGrace { get; set; }
    public int? MinimumDaysInPeriodB4fees { get; set; }
    public decimal? Provision4LiquidationRate { get; set; }
    public bool? SummarizePortfolioStatement { get; set; }
    public bool? UseNetDividend4Valuation { get; set; }
    public string? ShortCompanyName { get; set; }
    public string? WitholdTaxGlActNo { get; set; }
    public bool? ValuateDeposit4SharesAtMarketPrice { get; set; }
    public bool? AutoPortfolioCode { get; set; }
    public string? BrokerPayableActNo { get; set; }
    public string? BrokerReceivableActNo { get; set; }
    public string? BrokerPayable2ActNo { get; set; }
    public string? BrokerReceivable2ActNo { get; set; }
    public string? IntRecableActNo { get; set; }
    public string? XmlexportPath { get; set; }
    public bool? ReportPayRecAbleInValutaion { get; set; }
    public string? PfcBankCode { get; set; }
    public bool? ClosedPfa { get; set; }
    public string? XmlAuthorisedSignatory { get; set; }
    public string? Cash1AccountNo { get; set; }
    public string? Cash2AccountNo { get; set; }
    public int? PostChangeInShareValue { get; set; }
    public byte[]? Logo { get; set; }
    public string? StockBrokerTableName { get; set; }
    public bool? DividendReduceCost { get; set; }
}
